# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Category(object):
    def setupUi(self, Category):
        Category.setObjectName("Category")
        Category.resize(372, 300)
        self.label = QtWidgets.QLabel(Category)
        self.label.setGeometry(QtCore.QRect(160, 10, 81, 16))
        self.label.setObjectName("label")
        self.id_cat = QtWidgets.QLineEdit(Category)
        self.id_cat.setGeometry(QtCore.QRect(170, 50, 91, 20))
        self.id_cat.setText("")
        self.id_cat.setObjectName("id_cat")
        self.name_cat = QtWidgets.QLineEdit(Category)
        self.name_cat.setGeometry(QtCore.QRect(170, 90, 91, 20))
        self.name_cat.setText("")
        self.name_cat.setObjectName("name_cat")
        self.add_cat = QtWidgets.QPushButton(Category)
        self.add_cat.setGeometry(QtCore.QRect(270, 40, 75, 23))
        self.add_cat.setObjectName("add_cat")
        self.del_cat = QtWidgets.QPushButton(Category)
        self.del_cat.setGeometry(QtCore.QRect(270, 70, 75, 23))
        self.del_cat.setObjectName("del_cat")
        self.back_cat = QtWidgets.QPushButton(Category)
        self.back_cat.setGeometry(QtCore.QRect(270, 100, 75, 23))
        self.back_cat.setObjectName("back_cat")
        self.label_2 = QtWidgets.QLabel(Category)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Category)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.label_3.setObjectName("label_3")
        self.logs = QtWidgets.QTextEdit(Category)
        self.logs.setGeometry(QtCore.QRect(10, 140, 351, 151))
        self.logs.setObjectName("logs")

        self.retranslateUi(Category)
        QtCore.QMetaObject.connectSlotsByName(Category)

    def retranslateUi(self, Category):
        _translate = QtCore.QCoreApplication.translate
        Category.setWindowTitle(_translate("Category", "Form"))
        self.label.setText(_translate("Category", "Категории"))
        self.add_cat.setText(_translate("Category", "Добавить"))
        self.del_cat.setText(_translate("Category", "Удалить"))
        self.back_cat.setText(_translate("Category", "Назад"))
        self.label_2.setText(_translate("Category", "ID категории"))
        self.label_3.setText(_translate("Category", "Наименование категории"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Category = QtWidgets.QWidget()
    ui = Ui_Category()
    ui.setupUi(Category)
    Category.show()
    sys.exit(app.exec_())
