# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Enter(object):
    def setupUi(self, Enter):
        Enter.setObjectName("Enter")
        Enter.resize(365, 198)
        self.label = QtWidgets.QLabel(Enter)
        self.label.setGeometry(QtCore.QRect(170, 0, 111, 61))
        self.label.setObjectName("label")
        self.enter = QtWidgets.QPushButton(Enter)
        self.enter.setGeometry(QtCore.QRect(140, 140, 81, 23))
        self.enter.setObjectName("enter")
        self.email = QtWidgets.QLineEdit(Enter)
        self.email.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.email.setText("")
        self.email.setObjectName("email")
        self.pass_email = QtWidgets.QLineEdit(Enter)
        self.pass_email.setGeometry(QtCore.QRect(130, 110, 113, 20))
        self.pass_email.setObjectName("pass_email")
        self.label_2 = QtWidgets.QLabel(Enter)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Enter)
        self.label_3.setGeometry(QtCore.QRect(70, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.reg_avt = QtWidgets.QPushButton(Enter)
        self.reg_avt.setGeometry(QtCore.QRect(140, 170, 81, 23))
        self.reg_avt.setObjectName("reg_avt")

        self.retranslateUi(Enter)
        QtCore.QMetaObject.connectSlotsByName(Enter)

    def retranslateUi(self, Enter):
        _translate = QtCore.QCoreApplication.translate
        Enter.setWindowTitle(_translate("Enter", "Dialog"))
        self.label.setText(_translate("Enter", "Вход"))
        self.enter.setText(_translate("Enter", "Вход"))
        self.label_2.setText(_translate("Enter", "Email:"))
        self.label_3.setText(_translate("Enter", "Пароль:"))
        self.reg_avt.setText(_translate("Enter", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Enter = QtWidgets.QDialog()
    ui = Ui_Enter()
    ui.setupUi(Enter)
    Enter.show()
    sys.exit(app.exec_())
