# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MarketingResearches.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mar_Res(object):
    def setupUi(self, Mar_Res):
        Mar_Res.setObjectName("Mar_Res")
        Mar_Res.resize(440, 305)
        self.add_m = QtWidgets.QPushButton(Mar_Res)
        self.add_m.setGeometry(QtCore.QRect(304, 40, 101, 23))
        self.add_m.setObjectName("add_m")
        self.del_m = QtWidgets.QPushButton(Mar_Res)
        self.del_m.setGeometry(QtCore.QRect(304, 70, 101, 23))
        self.del_m.setObjectName("del_m")
        self.back_m = QtWidgets.QPushButton(Mar_Res)
        self.back_m.setGeometry(QtCore.QRect(304, 100, 101, 23))
        self.back_m.setObjectName("back_m")
        self.label = QtWidgets.QLabel(Mar_Res)
        self.label.setGeometry(QtCore.QRect(140, 10, 171, 16))
        self.label.setObjectName("label")
        self.id_m = QtWidgets.QLineEdit(Mar_Res)
        self.id_m.setGeometry(QtCore.QRect(170, 40, 121, 21))
        self.id_m.setText("")
        self.id_m.setObjectName("id_m")
        self.name_m = QtWidgets.QLineEdit(Mar_Res)
        self.name_m.setGeometry(QtCore.QRect(170, 70, 121, 21))
        self.name_m.setText("")
        self.name_m.setObjectName("name_m")
        self.cap_m = QtWidgets.QLineEdit(Mar_Res)
        self.cap_m.setGeometry(QtCore.QRect(170, 100, 121, 31))
        self.cap_m.setText("")
        self.cap_m.setObjectName("cap_m")
        self.label_2 = QtWidgets.QLabel(Mar_Res)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Mar_Res)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Mar_Res)
        self.label_4.setGeometry(QtCore.QRect(20, 105, 151, 21))
        self.label_4.setObjectName("label_4")
        self.logs = QtWidgets.QTextEdit(Mar_Res)
        self.logs.setGeometry(QtCore.QRect(10, 140, 421, 161))
        self.logs.setObjectName("logs")

        self.retranslateUi(Mar_Res)
        QtCore.QMetaObject.connectSlotsByName(Mar_Res)

    def retranslateUi(self, Mar_Res):
        _translate = QtCore.QCoreApplication.translate
        Mar_Res.setWindowTitle(_translate("Mar_Res", "Form"))
        self.add_m.setText(_translate("Mar_Res", "Добавить"))
        self.del_m.setText(_translate("Mar_Res", "Удалить"))
        self.back_m.setText(_translate("Mar_Res", "Назад"))
        self.label.setText(_translate("Mar_Res", "Маркетинговые исследования"))
        self.label_2.setText(_translate("Mar_Res", "ID исследования"))
        self.label_3.setText(_translate("Mar_Res", "Название исследования"))
        self.label_4.setText(_translate("Mar_Res", "Описание исследования"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mar_Res = QtWidgets.QWidget()
    ui = Ui_Mar_Res()
    ui.setupUi(Mar_Res)
    Mar_Res.show()
    sys.exit(app.exec_())
