# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(452, 242)
        self.category = QtWidgets.QPushButton(Menu)
        self.category.setGeometry(QtCore.QRect(320, 50, 91, 41))
        self.category.setObjectName("category")
        self.clients = QtWidgets.QPushButton(Menu)
        self.clients.setGeometry(QtCore.QRect(170, 140, 101, 41))
        self.clients.setObjectName("clients")
        self.mark_res = QtWidgets.QPushButton(Menu)
        self.mark_res.setGeometry(QtCore.QRect(120, 70, 191, 51))
        self.mark_res.setObjectName("mark_res")
        self.order_details = QtWidgets.QPushButton(Menu)
        self.order_details.setGeometry(QtCore.QRect(10, 50, 101, 41))
        self.order_details.setObjectName("order_details")
        self.order = QtWidgets.QPushButton(Menu)
        self.order.setGeometry(QtCore.QRect(10, 110, 101, 41))
        self.order.setObjectName("order")
        self.product = QtWidgets.QPushButton(Menu)
        self.product.setGeometry(QtCore.QRect(320, 110, 91, 41))
        self.product.setObjectName("product")
        self.label = QtWidgets.QLabel(Menu)
        self.label.setGeometry(QtCore.QRect(170, 10, 91, 21))
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(Menu)
        self.exit.setGeometry(QtCore.QRect(180, 200, 75, 23))
        self.exit.setObjectName("exit")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.category.setText(_translate("Menu", "Категории"))
        self.clients.setText(_translate("Menu", "Клиенты"))
        self.mark_res.setText(_translate("Menu", "Маркетинговые исследования"))
        self.order_details.setText(_translate("Menu", "Детали заказа"))
        self.order.setText(_translate("Menu", "Заказы"))
        self.product.setText(_translate("Menu", "Продукты"))
        self.label.setText(_translate("Menu", "Выбор таблицы"))
        self.exit.setText(_translate("Menu", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
