# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderdetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ord_Det(object):
    def setupUi(self, Ord_Det):
        Ord_Det.setObjectName("Ord_Det")
        Ord_Det.resize(400, 366)
        self.del_od = QtWidgets.QPushButton(Ord_Det)
        self.del_od.setGeometry(QtCore.QRect(270, 80, 75, 23))
        self.del_od.setObjectName("del_od")
        self.back_od = QtWidgets.QPushButton(Ord_Det)
        self.back_od.setGeometry(QtCore.QRect(270, 110, 75, 23))
        self.back_od.setObjectName("back_od")
        self.add_od = QtWidgets.QPushButton(Ord_Det)
        self.add_od.setGeometry(QtCore.QRect(270, 50, 75, 23))
        self.add_od.setObjectName("add_od")
        self.id_ord_det = QtWidgets.QLineEdit(Ord_Det)
        self.id_ord_det.setEnabled(True)
        self.id_ord_det.setGeometry(QtCore.QRect(142, 30, 61, 20))
        self.id_ord_det.setMouseTracking(True)
        self.id_ord_det.setTabletTracking(False)
        self.id_ord_det.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.id_ord_det.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.id_ord_det.setAcceptDrops(True)
        self.id_ord_det.setAutoFillBackground(False)
        self.id_ord_det.setText("")
        self.id_ord_det.setFrame(True)
        self.id_ord_det.setDragEnabled(False)
        self.id_ord_det.setReadOnly(False)
        self.id_ord_det.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.id_ord_det.setClearButtonEnabled(False)
        self.id_ord_det.setObjectName("id_ord_det")
        self.id_prod_o = QtWidgets.QLineEdit(Ord_Det)
        self.id_prod_o.setGeometry(QtCore.QRect(142, 90, 61, 20))
        self.id_prod_o.setText("")
        self.id_prod_o.setObjectName("id_prod_o")
        self.count = QtWidgets.QLineEdit(Ord_Det)
        self.count.setGeometry(QtCore.QRect(142, 120, 61, 20))
        self.count.setText("")
        self.count.setObjectName("count")
        self.price = QtWidgets.QLineEdit(Ord_Det)
        self.price.setGeometry(QtCore.QRect(142, 150, 61, 20))
        self.price.setText("")
        self.price.setObjectName("price")
        self.id_order = QtWidgets.QLineEdit(Ord_Det)
        self.id_order.setGeometry(QtCore.QRect(142, 60, 61, 20))
        self.id_order.setText("")
        self.id_order.setObjectName("id_order")
        self.label = QtWidgets.QLabel(Ord_Det)
        self.label.setGeometry(QtCore.QRect(160, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Ord_Det)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Ord_Det)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Ord_Det)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Ord_Det)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Ord_Det)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 111, 16))
        self.label_6.setObjectName("label_6")
        self.logs = QtWidgets.QTextEdit(Ord_Det)
        self.logs.setGeometry(QtCore.QRect(20, 190, 361, 161))
        self.logs.setReadOnly(True)
        self.logs.setObjectName("logs")

        self.retranslateUi(Ord_Det)
        QtCore.QMetaObject.connectSlotsByName(Ord_Det)

    def retranslateUi(self, Ord_Det):
        _translate = QtCore.QCoreApplication.translate
        Ord_Det.setWindowTitle(_translate("Ord_Det", "Form"))
        self.del_od.setText(_translate("Ord_Det", "Удалить"))
        self.back_od.setText(_translate("Ord_Det", "Назад"))
        self.add_od.setText(_translate("Ord_Det", "Добавить"))
        self.label.setText(_translate("Ord_Det", "Детали заказа"))
        self.label_2.setText(_translate("Ord_Det", "ID деталей заказа"))
        self.label_3.setText(_translate("Ord_Det", "ID заказа"))
        self.label_4.setText(_translate("Ord_Det", "ID продукта"))
        self.label_5.setText(_translate("Ord_Det", "Количество"))
        self.label_6.setText(_translate("Ord_Det", "Цена за единицу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ord_Det = QtWidgets.QWidget()
    ui = Ui_Ord_Det()
    ui.setupUi(Ord_Det)
    Ord_Det.show()
    sys.exit(app.exec_())
